<?php

namespace AppBundle\Repository;

/**
 * ConfigOptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigOptionRepository extends \Doctrine\ORM\EntityRepository
{
}
