<?php

namespace AppBundle\Repository;

/**
 * ImageTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
